DEPEN = grovepi.o grovepi_sound_sensor.o grovepi_digital_read.o grovepi_analog_read.o grovepi_digital_write.o
INC = ~/dev/GrovePi-EE250/Software/Cpp/
SRC = grovepi.cpp grove_sound_sensor.cpp grovepi_digital_read.cpp grovepi_analog_read.cpp grovepi_digital_write.cpp

all:
	g++ -Wall -I $(INC) $(SRC) -o sound_sense
